version: '3.8'

services:
  kms-ai-flow:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_DAILY_USAGE_LIMIT=5
      - NEXT_PUBLIC_MAX_CHARS=20000
    restart: unless-stopped
    container_name: kms-ai-flow
